### ISSUE TITLE
How to get Miro User ID during REST API authentication from Miro's Web SDK authorization

### ISSUE THREAD

**Issue by BentleyDavis** [miroapp/api-clients#66]
When following the [REST API authentication from Miro's Web SDK authorization](https://developers.miro.com/docs/enable_api_authentication_from_sdk_authorization) and using the api-client I'm having trouble finding the Miro User ID in time so I can look up my externalUserId. 

In the normal API flow we would put the external ID in the state or the callback URL but in the app auth flow the redirect URL is sent by Miro based on a static field in the app settings so we can't add a unique state on each URL. If we use the `exchangeCodeForAccessToken` the Miro UserId is hidden. I need the Miro UserId to find my external ID in my database early in the process. I spoke to Joseph during his presentation at the  Miro Developer Q/A in Discord and  he thought `exchangeCodeForAccessToken` might be changed to return the Miro User ID like:

```const { userId } = await miro.exchangeCodeForAccessToken(ExternalUserId, code)```

although, I'm thinking I need the Miro UserId before I call exchangeCodeForAccessToken so I can look up and send my external ID to exchangeCodeForAccessToken.

We were hoping to deploy this week. If that change is made how soon could it be done? Is there a suggested workaround? Or should I call back to not using the api-client for the APP Auth flow?

**Comment by BentleyDavis** [comment]
Discussion Thread on [Discord](https://discord.com/channels/933103778855534614/1037415318357807345)

Looking at it further, It seems the flow assumes there is an external User ID. We are simply using this to access the API during the use of the SDK so we would prefer not to have the extra overhead of generating, maintaining a separate ID from the Miro ID and having the extra lookup tables and database hits. This is already a convoluted way to call functions that are only on the API and will probably eventually be moved to the SDK. Suggestions appreciated.

**Comment by janza** [comment]
Hi @BentleyDavis, 
I am assuming that you don't have any kind of session on the server, so it might be useful to use the id tokens generated on SDK to pass user ids from miro to you server backend: https://developers.miro.com/docs/board_board#getidtoken
You can use this with the `jsonwebtoken` library to get and verify the user id based on the app secret:

```javascript
const jwt  = require('jsonwebtoken');

// in request handler - given the id token is passed as a query parameter
const {user} = jwt.verify(req.query.idToken, process.env.MIRO_CLIENT_SECRET)

const api = miro.as(user)
const board = await api.getBoard(...)
```

When exchanging the token you can pass an empty id:
```javascript
await miro.exchangeCodeForAccessToken('', code)
```

And your storage `set()` implementation can use the `userId` from the `state`:
```javascript
class Storage {
  set(_ignoreMe, state) {
    const userId = state.userId

    await database.store(userId, state)
  }
  ...
}
```

**Comment by BentleyDavis** [comment]
@janza , I'm a little confused. How can I call [getidtoken](https://developers.miro.com/docs/board_board#getidtoken) in my app app if the [Web SDK authorization](https://developers.miro.com/docs/enable_api_authentication_from_sdk_authorization) hasn't started my app yet?

**Comment by janza** [comment]
Indeed, that is only available after the authorization. For the authorization step you can pass an empty userId to the `exchangeCodeForAccessToken` method as suggested above.

**Comment by BentleyDavis** [comment]
For clarification in case anyone else needs this:
> When exchanging the **Code for an Access Token** you can pass an empty **externalId**:
> 
> await miro.exchangeCodeForAccessToken('', code)
> And your storage set() implementation can use the userId from the state:
> 
> class Storage {
>   set(_ignoreMe, state) {
>     const userId = state.userId
> 
>     await database.store(userId, state)
>   }
>  

Mentioning the jsonwebtoken first is confusing when it is needed later in the process in a different endpoint.

I guess this is closed as a work around. Updated documentation would be helpful as this is one of the recommended ways to use the API from the SDK but the design of the api-client is misleading in this scenario.
